/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

import static Questions.Magic8Ball.askQuestion;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ethan
 */
public class Magic8BallGUI extends javax.swing.JFrame {
    /**
     * Creates new form Magic8BallGUI
     */
    public Magic8BallGUI() {
        super.setSize(458, 492);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionLabel = new javax.swing.JLabel();
        answerLabel = new javax.swing.JTextArea();
        questionTextField = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        shakeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(440, 480, 480, 480));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(480, 530));
        setSize(new java.awt.Dimension(498, 480));
        getContentPane().setLayout(null);

        questionLabel.setText("Ask a question:");
        getContentPane().add(questionLabel);
        questionLabel.setBounds(21, 429, 74, 14);

        answerLabel.setEditable(false);
        answerLabel.setBackground(new java.awt.Color(0, 0, 0));
        answerLabel.setColumns(20);
        answerLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        answerLabel.setForeground(new java.awt.Color(255, 255, 255));
        answerLabel.setLineWrap(true);
        answerLabel.setRows(5);
        answerLabel.setWrapStyleWord(true);
        answerLabel.setBorder(null);
        answerLabel.setOpaque(false);
        getContentPane().add(answerLabel);
        answerLabel.setBounds(160, 150, 140, 140);

        questionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(questionTextField);
        questionTextField.setBounds(114, 416, 261, 30);

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Questions/magiceightball.png"))); // NOI18N
        getContentPane().add(imageLabel);
        imageLabel.setBounds(29, 11, 400, 400);

        shakeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shakeButton.setText("Shake the 8-BALL!");
        shakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shakeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shakeButton);
        shakeButton.setBounds(120, 460, 250, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionTextFieldActionPerformed

    private void shakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shakeButtonActionPerformed
        // TODO add your handling code here:
        String question = questionTextField.getText();
        String answer = askQuestion(question);
        answerLabel.setText(answer);
    }//GEN-LAST:event_shakeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Magic8BallGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Magic8BallGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answerLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JTextField questionTextField;
    private javax.swing.JButton shakeButton;
    // End of variables declaration//GEN-END:variables
}
