/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;

import static Questions.ScrabbleScore.calculateScore;
import java.awt.Color;

/**
 *
 * @author Ethan
 */
public class ScrabbleCalculator extends javax.swing.JFrame {

    /**
     * Creates new form ScrabbleCalculator
     */
    public ScrabbleCalculator() {
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        wordInputTextField = new javax.swing.JTextField();
        wordInputLabel = new javax.swing.JLabel();
        scoreOutputLabel = new javax.swing.JLabel();
        scoreOutputLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(null);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(" Enter your word  inside the \"Word\" box. Click the submit button. Then watch the magic happen. Your score will show up next to the \"Score\" info label.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(75, 75, 75));
        jTextArea1.setFocusable(false);
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 170, 140));

        wordInputTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wordInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordInputTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(wordInputTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 100, -1));

        wordInputLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wordInputLabel.setText("Word:");
        getContentPane().add(wordInputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        scoreOutputLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scoreOutputLabel.setText("Score:");
        getContentPane().add(scoreOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        scoreOutputLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(scoreOutputLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 100, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 340, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Questions/Untitled-1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wordInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordInputTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String word = wordInputTextField.getText();
        int score = calculateScore(word);
        if(isAlpha(word))
            scoreOutputLabel2.setText("" + score);
        else
            scoreOutputLabel2.setText("Invalid");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScrabbleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScrabbleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScrabbleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScrabbleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrabbleCalculator().setVisible(true);
            }
        });
    }
    public boolean isAlpha(String word) {
        return word.matches("[\\sa-zA-Z]+");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel scoreOutputLabel;
    private javax.swing.JLabel scoreOutputLabel2;
    private javax.swing.JLabel wordInputLabel;
    private javax.swing.JTextField wordInputTextField;
    // End of variables declaration//GEN-END:variables
}
